site_name: ISO 27001 Lead Auditor Project (Simulation)
site_description: End-to-end ISO 27001 audit simulation and continuous compliance concept
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - content.code.copy
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: blue
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list

nav:
  - Home: index.md
  - Company Profile: 01-company-profile.md
  - ISMS Scope: 02-isms-scope.md
  - Evidence Reviewed: 03-evidence-reviewed.md
  - Audit Checklist: 04-audit-checklist.md
  - Audit Report: 05-audit-report.md
  - Statement of Applicability: 06-statement-of-applicability.md
  - Risk Register (Sample): 07-risk-register-sample.md
  - Compliance Dashboard: 08-compliance-dashboard.md
  - Annex A Checklist: 09-annex-a-checklist.md
